[workspace]
members = ["core", "node", "mobile", "commands"]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.0.1"
authors = ["luoluoqixi"]
repository = "https://github.com/lona-labs/lonanote"
license = ""

[workspace.dependencies]
serde = "1.0.217"
serde_json = "1.0.138"
tokio = { version = "1.43.0", features = ["full"] }
async-trait = "0.1.86"
anyhow = "1.0.95"
log = "0.4.25"
thiserror = "2.0.11"
notify = "8.0.0"
ignore = "0.4.23"
fs_extra = "1.3.0"

[profile.release]
codegen-units = 1 # Compile crates one after another so the compiler can optimize better
lto = true        # Enables link to optimizations
opt-level = "s"   # Optimize for binary size
panic = "abort"   # Higher performance by disabling panic handlers.
strip = true      # Remove debug symbols
