/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function sum(a: number, b: number): number
export declare function invoke(key: string, args?: string | undefined | null): string | null
export declare function invokeAsync(key: string, args?: string | undefined | null): Promise<string | null>
export declare function init(): string | null
